//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESLEntities : DbContext
    {
        public ESLEntities()
            : base("name=ESLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Code> Tbl_Code { get; set; }
        public virtual DbSet<Tbl_CodeGroup> Tbl_CodeGroup { get; set; }
        public virtual DbSet<Tbl_Contract> Tbl_Contract { get; set; }
        public virtual DbSet<Tbl_Course> Tbl_Course { get; set; }
        public virtual DbSet<Tbl_Document> Tbl_Document { get; set; }
        public virtual DbSet<Tbl_Exam> Tbl_Exam { get; set; }
        public virtual DbSet<Tbl_ExamInPerson> Tbl_ExamInPerson { get; set; }
        public virtual DbSet<Tbl_Gallery> Tbl_Gallery { get; set; }
        public virtual DbSet<Tbl_GalleryDocument> Tbl_GalleryDocument { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_News> Tbl_News { get; set; }
        public virtual DbSet<Tbl_NewsDocument> Tbl_NewsDocument { get; set; }
        public virtual DbSet<Tbl_Organization> Tbl_Organization { get; set; }
        public virtual DbSet<Tbl_Page> Tbl_Page { get; set; }
        public virtual DbSet<Tbl_Payment> Tbl_Payment { get; set; }
        public virtual DbSet<Tbl_Question> Tbl_Question { get; set; }
        public virtual DbSet<Tbl_Region> Tbl_Region { get; set; }
        public virtual DbSet<Tbl_Response> Tbl_Response { get; set; }
        public virtual DbSet<Tbl_Role> Tbl_Role { get; set; }
        public virtual DbSet<Tbl_SubCourse> Tbl_SubCourse { get; set; }
        public virtual DbSet<Tbl_SubMenu> Tbl_SubMenu { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_UserExam> Tbl_UserExam { get; set; }
        public virtual DbSet<Tbl_UserExamAccess> Tbl_UserExamAccess { get; set; }
        public virtual DbSet<Tbl_UserExamInPerson> Tbl_UserExamInPerson { get; set; }
    }
}
