//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Exam()
        {
            this.Tbl_UserExam = new HashSet<Tbl_UserExam>();
            this.Tbl_UserExamAccess = new HashSet<Tbl_UserExamAccess>();
        }
    
        public int Exam_ID { get; set; }
        public System.Guid Exam_Guid { get; set; }
        public int Exam_QuestionID { get; set; }
        public string Exam_Title { get; set; }
        public int Exam_Mark { get; set; }
        public int Exam_PassMark { get; set; }
        public System.DateTime Exam_CreationDate { get; set; }
        public System.DateTime Exam_ModifiedDate { get; set; }
        public bool Exam_IsDelete { get; set; }
    
        public virtual Tbl_Question Tbl_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserExam> Tbl_UserExam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserExamAccess> Tbl_UserExamAccess { get; set; }
    }
}
