//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_News = new HashSet<Tbl_News>();
        }
    
        public int User_ID { get; set; }
        public System.Guid User_Guid { get; set; }
        public int User_RoleID { get; set; }
        public int User_GenderCodeID { get; set; }
        public string User_UserName { get; set; }
        public string User_Email { get; set; }
        public bool User_EmailConfirmed { get; set; }
        public string User_PasswordHash { get; set; }
        public string User_SecurityStamp { get; set; }
        public string User_PhoneNumber { get; set; }
        public bool User_PhoneNumberConfirmed { get; set; }
        public bool User_TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> User_LockoutEndDateUtc { get; set; }
        public bool User_LockoutEnabled { get; set; }
        public int User_AccessFailedCount { get; set; }
        public string User_FirstName { get; set; }
        public string User_lastName { get; set; }
        public string User_IdentityNumber { get; set; }
        public string User_Telephone { get; set; }
        public string User_Address { get; set; }
        public string User_PostalCode { get; set; }
        public bool User_IsBan { get; set; }
        public bool User_IsDelete { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_News> Tbl_News { get; set; }
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
