//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NewsDocument
    {
        public int ND_ID { get; set; }
        public System.Guid ND_Guid { get; set; }
        public int ND_NewsID { get; set; }
        public int ND_DocumentID { get; set; }
        public int ND_TypeCodeID { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Document Tbl_Document { get; set; }
        public virtual Tbl_News Tbl_News { get; set; }
    }
}
