//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Course()
        {
            this.Tbl_SubCourse = new HashSet<Tbl_SubCourse>();
        }
    
        public int Course_ID { get; set; }
        public System.Guid Course_Guid { get; set; }
        public int Course_DocumentID { get; set; }
        public string Course_Title { get; set; }
        public string Course_Abstract { get; set; }
        public string Course_Description { get; set; }
        public System.DateTime Course_CreationDate { get; set; }
        public System.DateTime Course_ModifiedDate { get; set; }
        public bool Course_IsDelete { get; set; }
    
        public virtual Tbl_Document Tbl_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SubCourse> Tbl_SubCourse { get; set; }
    }
}
