//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserClass
    {
        public int UC_ID { get; set; }
        public System.Guid UC_Guid { get; set; }
        public int UC_UserID { get; set; }
        public int UC_CPID { get; set; }
        public Nullable<int> UC_PaymentID { get; set; }
        public System.DateTime UC_CreationDate { get; set; }
        public System.DateTime UC_ModifiedDate { get; set; }
        public bool UC_IsDelete { get; set; }
    
        public virtual Tbl_ClassPlan Tbl_ClassPlan { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
