//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Region
    {
        public int Region_ID { get; set; }
        public System.Guid Region_Guid { get; set; }
        public int Region_PageID { get; set; }
        public Nullable<int> Region_DocumentID { get; set; }
        public string Region_Name { get; set; }
        public string Region_Title { get; set; }
        public string Region_Description { get; set; }
        public bool Region_HasDocument { get; set; }
    
        public virtual Tbl_Document Tbl_Document { get; set; }
        public virtual Tbl_Page Tbl_Page { get; set; }
    }
}
