//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Document()
        {
            this.Tbl_Contract = new HashSet<Tbl_Contract>();
            this.Tbl_Course = new HashSet<Tbl_Course>();
            this.Tbl_Gallery = new HashSet<Tbl_Gallery>();
            this.Tbl_GalleryDocument = new HashSet<Tbl_GalleryDocument>();
            this.Tbl_NewsDocument = new HashSet<Tbl_NewsDocument>();
            this.Tbl_Organization = new HashSet<Tbl_Organization>();
            this.Tbl_Region = new HashSet<Tbl_Region>();
            this.Tbl_SubCourse = new HashSet<Tbl_SubCourse>();
        }
    
        public int Document_ID { get; set; }
        public System.Guid Document_Guid { get; set; }
        public int Document_TypeCodeID { get; set; }
        public string Document_Path { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Contract> Tbl_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Course> Tbl_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Gallery> Tbl_Gallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_GalleryDocument> Tbl_GalleryDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_NewsDocument> Tbl_NewsDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Organization> Tbl_Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Region> Tbl_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SubCourse> Tbl_SubCourse { get; set; }
    }
}
