//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SubCourse
    {
        public int SC_ID { get; set; }
        public System.Guid SC_Guid { get; set; }
        public int SC_CourseID { get; set; }
        public int SC_DocumentID { get; set; }
        public string SC_Title { get; set; }
        public string SC_Abstract { get; set; }
        public string SC_Description { get; set; }
        public System.DateTime SC_CreationDate { get; set; }
        public System.DateTime SC_ModifiedDate { get; set; }
        public bool SC_IsDelete { get; set; }
    
        public virtual Tbl_Course Tbl_Course { get; set; }
        public virtual Tbl_Document Tbl_Document { get; set; }
    }
}
