//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserClassPresence
    {
        public int UCP_ID { get; set; }
        public System.Guid UCP_Guid { get; set; }
        public int UCP_UCID { get; set; }
        public int UCP_PaymentID { get; set; }
        public bool UCP_IsPresent { get; set; }
        public System.DateTime UCP_Date { get; set; }
        public System.DateTime UCP_CreationDate { get; set; }
        public System.DateTime UCP_ModifiedDate { get; set; }
        public bool UCP_IsDelete { get; set; }
    
        public virtual Tbl_Payment Tbl_Payment { get; set; }
        public virtual Tbl_UserClass Tbl_UserClass { get; set; }
    }
}
