//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contract
    {
        public int Contract_ID { get; set; }
        public System.Guid Contract_Guid { get; set; }
        public int Contract_DocumentID { get; set; }
        public int Contract_TypeCodeID { get; set; }
        public string Contract_Title { get; set; }
        public string Contract_Description { get; set; }
        public System.DateTime Contract_CreationDate { get; set; }
        public System.DateTime Contract_ModifiedDate { get; set; }
        public bool Contract_IsDelete { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        public virtual Tbl_Document Tbl_Document { get; set; }
    }
}
