//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserExamAccess
    {
        public int UEA_ID { get; set; }
        public System.Guid UEA_Guid { get; set; }
        public int UEA_UserID { get; set; }
        public int UEA_ExamID { get; set; }
        public System.DateTime UEA_Date { get; set; }
        public bool UEA_IsActive { get; set; }
        public bool UEA_IsDelete { get; set; }
    
        public virtual Tbl_Exam Tbl_Exam { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
