//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserExam
    {
        public int UE_ID { get; set; }
        public System.Guid UE_Guid { get; set; }
        public int UE_UserID { get; set; }
        public int UE_ERID { get; set; }
        public int UE_Mark { get; set; }
        public System.DateTime UE_Date { get; set; }
        public bool UE_IsDelete { get; set; }
    
        public virtual Tbl_ExamRemotely Tbl_ExamRemotely { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
