//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SubExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SubExam()
        {
            this.Tbl_ExamInPerson = new HashSet<Tbl_ExamInPerson>();
        }
    
        public int SE_ID { get; set; }
        public System.Guid SE_Guid { get; set; }
        public int SE_ExamID { get; set; }
        public string SE_Title { get; set; }
        public System.DateTime SE_CreationDate { get; set; }
        public System.DateTime SE_ModifiedDate { get; set; }
        public bool SE_IsDelete { get; set; }
    
        public virtual Tbl_Exam Tbl_Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ExamInPerson> Tbl_ExamInPerson { get; set; }
    }
}
