//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESL.DataLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ExamRemotely
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ExamRemotely()
        {
            this.Tbl_Question = new HashSet<Tbl_Question>();
            this.Tbl_UserExam = new HashSet<Tbl_UserExam>();
            this.Tbl_UserExamAccess = new HashSet<Tbl_UserExamAccess>();
        }
    
        public int ER_ID { get; set; }
        public System.Guid ER_Guid { get; set; }
        public int ER_GroupCodeID { get; set; }
        public string ER_Title { get; set; }
        public int ER_Mark { get; set; }
        public int ER_PassMark { get; set; }
        public System.DateTime ER_CreationDate { get; set; }
        public System.DateTime ER_ModifiedDate { get; set; }
        public bool ER_IsDelete { get; set; }
    
        public virtual Tbl_Code Tbl_Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Question> Tbl_Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserExam> Tbl_UserExam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserExamAccess> Tbl_UserExamAccess { get; set; }
    }
}
